---
Name: silverstripe-cookie-consent
Before:
  - mysite
After:
  - coreconfig
  - cmsextensions
---
PageController:
  extensions:
  - Nomidi\CookieConsent\CookieConsentExtension

SilverStripe\SiteConfig\SiteConfig:
  extensions:
  - Nomidi\CookieConsent\CookieConsentSettings
